version: '3.1'

services:
  websocket:
    restart: always
    build:
      context: /
      dockerfile: ./Dockerfile
    working_dir: /websocket
    expose:
      - "8090"
    command: mvn clean spring-boot:run

